title: Nikhil's Nighthawk Page
description: "Class of 2027"
owner_name: Nikhil Narayan
github_username: nikhilsna
github_repo: "nikhil-2025" 
baseurl: "/nikhil-2026"
future: true
#remote_theme: jekyll/minima
minima:
  skin: dark
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/journey.md
  - navigation/calculator.md
  - navigation/tasklist.md
  - navigation/cookieclicker.md
  - navigation/snakegame.md
  - _notebooks/problems
  - _notebooks/python
  - _notebooks/javascript
  - _notebooks/itloop
  - _notebooks/whileloop
  - _notebooks/listdict
  - _notebooks/pyhack
  - _notebooks/jshack3.7
  - _notebooks/pyhack3.7
  - _notebooks/pyhack3.2
  - _notebooks/pyhack3.5
  - _notebooks/pyhack3.3
  - _notebooks/pophack3.10
  - _notebooks/hack3.10
  - _notebooks/jssprites
  - _notebooks/mcblog
  - _notebooks/pprblog
  - _notebooks/fretroblog
  - _notebooks/BHfx
  - _notebooks/crdsrc
  - _notebooks/sfcmtng/
  - _notebooks/pasprj/
  - _notebooks/lstflt/
  - _notebooks/simshw/
  - _notebooks/excred/
  - _notebooks/bigO/
  - _notebooks/styblg/
  - _notebooks/21MC/
  - _notebooks/undpr/
  - _notebooks/binary/
  - _notebooks/mlog/
  - _notebooks/po/
  - _notebooks/ps/
  - _notebooks/hw/
  - README4YML.md
